version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t kmean -f Dockerfile .

     # deploy the image
     - run: |  
         docker login --username=pinaki.best@gmail.com --password=8fe0c4d9-c792-4685-8d42-fa264e504f10 registry.heroku.com
         docker tag kmean registry.heroku.com/polar-brook-58047/web
         docker push registry.heroku.com/polar-brook-58047/web
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web --app polar-brook-58047
     
